const fs=require('fs'),assert=require('assert');
const root=__dirname+'/../../';
const c=fs.readFileSync(root+'scripts/map/map-feature-contract.js','utf8');
const s=fs.readFileSync(root+'scripts/map/map-feature-store.js','utf8');
const l=fs.readFileSync(root+'scripts/map/map-feature-library.js','utf8');
const p=fs.readFileSync(root+'scripts/map/map-package.js','utf8');
assert(c.includes('layerId') && c.includes('FORBIDDEN'));
assert(s.includes("transaction([LAYER_STORE,FEATURE_STORE]"));
assert(s.includes("index('layerId')"));
assert(!s.includes('render(') && !s.includes('GeoReference'));
assert(l.includes('MG1MapFeatureStore') && l.includes('createFeature'));
assert(p.includes("indexedDB.open(MAP_DB_NAME_, 4)"));
assert(p.includes("const FEATURE_DB_STORE_ = 'features'"));
assert(p.includes("createIndex('layerId', 'layerId'"));
console.log('PASS v25-feature-static.test.js');
