const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={console};ctx.globalThis=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../../scripts/map/map-feature-contract.js','utf8'),ctx);
const C=ctx.MG1MapFeatureContract;
let f=C.normalize({id:'f1',layerId:'l1',type:'point',geometry:{x:1},properties:{name:'A'}});
assert.deepStrictEqual(JSON.parse(JSON.stringify(f)),{id:'f1',layerId:'l1',type:'point',geometry:{x:1},properties:{name:'A'},schemaVersion:1});
assert.throws(()=>C.normalize({id:'f1'}),e=>e.code===C.errors.INVALID_LAYER_ID);
assert.throws(()=>C.validatePatch({layerId:'l2'}),e=>e.code===C.errors.FORBIDDEN_FIELD+':layerId');
assert.throws(()=>C.validatePatch({tiles:[]}),e=>e.code===C.errors.FORBIDDEN_FIELD+':tiles');
console.log('PASS v25-feature-contract.test.js');
