SCHEMA_VERSION="A.1"
SHEETS=["_Baseline","_System","_Lists","Equipment","WorkFront","Operations","Maintenance","Issues","Plans","HSE","AuditLog"]
DOMAIN_ENTITIES=["Equipment","WorkFront","Operations","Maintenance","Issues","Plans","HSE"]
HEADERS={
"Equipment":["equipment_id","category","type","owner_type","owner_name","status","effective_from","effective_to"],
"WorkFront":["work_front_id","domain","location","responsible","status","effective_from","effective_to"],
"Operations":["transaction_id","transaction_date","transaction_time","domain","work_front_id","equipment_id","activity","quantity","unit","actual_hours","target_hours","status","source","created_at","updated_at"],
"Maintenance":["maintenance_id","equipment_id","event_date","event_type","failure_code","start_time","end_time","downtime_hours","action","status","source"],
"Issues":["issue_id","issue_date","domain","work_front_id","equipment_id","description","severity","status","assigned_to","closed_at"],
"Plans":["plan_id","period","domain","work_front_id","activity","target_quantity","unit","target_hours","status"],
"HSE":["hse_id","event_date","domain","work_front_id","event_type","severity","description","action","status","closed_at"],
"AuditLog":["audit_id","timestamp","entity","entity_id","action","old_value","new_value","source"]}
PKS={"Equipment":"equipment_id","WorkFront":"work_front_id","Operations":"transaction_id","Maintenance":"maintenance_id","Issues":"issue_id","Plans":"plan_id","HSE":"hse_id","AuditLog":"audit_id"}
REQUIRED={"Equipment":{"equipment_id"},"WorkFront":{"work_front_id"},"Operations":{"transaction_id","work_front_id"},"Maintenance":{"maintenance_id","equipment_id"},"Issues":{"issue_id"},"Plans":{"plan_id"},"HSE":{"hse_id"}}
NUMERIC={"quantity","actual_hours","target_hours","downtime_hours","target_quantity"}
SYSTEM_FIELDS={"created_at","updated_at"}
FK={"Operations.work_front_id":("WorkFront","work_front_id",True),"Operations.equipment_id":("Equipment","equipment_id",False),"Maintenance.equipment_id":("Equipment","equipment_id",True),"Issues.work_front_id":("WorkFront","work_front_id",False),"Issues.equipment_id":("Equipment","equipment_id",False),"Plans.work_front_id":("WorkFront","work_front_id",False),"HSE.work_front_id":("WorkFront","work_front_id",False)}
CONTROLLED={"Equipment.category":"equipment_category","Equipment.type":"equipment_type","Equipment.owner_type":"owner_type","Equipment.status":"equipment_status","WorkFront.domain":"service_domain","WorkFront.status":"work_front_status","Operations.domain":"service_domain","Operations.unit":"unit","Operations.status":"transaction_status","Maintenance.event_type":"maintenance_event_type","Maintenance.action":"maintenance_event_type","Maintenance.status":"maintenance_status","Issues.domain":"service_domain","Issues.severity":"issue_severity","Issues.status":"issue_status","Plans.domain":"service_domain","Plans.unit":"unit","Plans.status":"plan_status","HSE.domain":"service_domain","HSE.event_type":"hse_event_type","HSE.severity":"hse_severity","HSE.action":"hse_event_type","HSE.status":"hse_status"}
